# Generated by Django 3.0.2 on 2021-11-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('device_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('temp', models.FloatField(default=0.0)),
                ('humid', models.FloatField(default=0.0)),
                ('moist', models.FloatField(default=0.0)),
            ],
        ),
    ]
